from pathlib import Path


class MarkdownExporter:

    def generate(

        self,

        project,

        summary,

        scores,

        security,

        ai_review=None,

    ):

        md = []

        md.append("# CodeInsight AI Report\n")

        md.append(f"## Files : {project['file_count']}")

        md.append(f"## Lines : {project['total_lines']}")

        md.append("")

        md.append("# Project Summary")

        md.append("")

        md.append(f"- Functions : {summary['functions']}")

        md.append(f"- Classes : {summary['classes']}")

        md.append("")

        md.append("# Quality")

        md.append("")

        md.append(f"- Overall : {scores['overall']}")

        md.append(f"- Documentation : {scores['documentation']}")

        md.append(f"- Maintainability : {scores['maintainability']}")

        md.append(f"- Readability : {scores['readability']}")

        md.append(f"- Architecture : {scores['architecture']}")

        md.append("")

        md.append("# Security")

        md.append("")

        md.append(f"Score : {security}")

        md.append("")

        if ai_review:

            md.append("# AI Review")

            md.append(ai_review)

        md.append("")

        md.append("---")

        md.append("Generated by CodeInsight AI")

        return "\n".join(md)

    def save(

        self,

        path,

        *args,

        **kwargs,

    ):

        text = self.generate(

            *args,

            **kwargs,

        )

        Path(path).write_text(

            text,

            encoding="utf-8",

        )

        return path