from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple


class ReadmeGenerator:
    """
    Generates a professional GitHub README for an analyzed project.

    The generator intentionally keeps the same public API as previous
    versions so existing exporters do not require changes.

    generate(
        project_name,
        summary,
        scores,
        stats,
        libraries
    )
    """

    GENERATED_BY = "CodeInsight AI"

    # ---------------------------------------------------------
    # Helper methods
    # ---------------------------------------------------------

    def _safe(self, value: Any, default: Any = "-") -> Any:
        """Safely return a value."""

        if value is None:
            return default

        if value == "":
            return default

        return value

    def _metric(self, dictionary: Dict[str, Any], key: str, default: Any = 0):
        return dictionary.get(key, default)

    def _badge(self, label: str, value: str, color: str) -> str:
        return (
            f"https://img.shields.io/badge/"
            f"{label}-{value}-{color}"
        )

    def _section(self, title: str) -> str:
        return f"\n---\n\n# {title}\n\n"

    def _table(
        self,
        headers: Iterable[str],
        rows: Iterable[Iterable[Any]],
    ) -> str:

        headers = list(headers)

        output = []

        output.append("| " + " | ".join(headers) + " |")

        output.append(
            "|" +
            "|".join(["---"] * len(headers))
            + "|"
        )

        for row in rows:
            output.append(
                "| "
                + " | ".join(str(x) for x in row)
                + " |"
            )

        return "\n".join(output)

    def _library_markdown(
        self,
        libraries: List[Tuple[str, int]]
    ) -> str:

        if not libraries:
            return "- No external libraries detected"

        lines = []

        for library, count in libraries:
            lines.append(
                f"- **{library}** ({count} imports)"
            )

        return "\n".join(lines)

    def _feature_list(self) -> str:

        features = [
            "Static Code Analysis",
            "Repository Analysis",
            "Dependency Graph",
            "Function Call Graph",
            "Cyclomatic Complexity Analysis",
            "Security Scanner",
            "Duplicate Code Detection",
            "TODO Detection",
            "Design Pattern Detection",
            "Automatic Documentation Metrics",
            "Repository Search",
            "AI Project Review",
            "PDF Report Export",
            "HTML Report Export",
            "Excel Report Export",
            "JSON Report Export",
            "README Generator",
        ]

        return "\n".join(
            f"- {feature}"
            for feature in features
        )

    def _installation(self) -> str:

        return """```bash
git clone <repository-url>

cd <repository>

python -m venv .venv

# Windows
.venv\\Scripts\\activate

# Linux / macOS
source .venv/bin/activate

pip install -r requirements.txt

streamlit run app.py
```"""

    def _usage(self) -> str:

        return """```text
1. Launch the Streamlit application.

2. Upload a repository.

3. Wait for analysis.

4. Explore:

   • Dashboard
   • Security
   • Complexity
   • Dependency Graph
   • Call Graph
   • Duplicate Detection
   • Repository Search
   • AI Review

5. Export reports as PDF, HTML, Excel,
   JSON or Markdown.
```"""

    def _architecture(self) -> str:

        return """```text
Repository
      │
      ▼
Project Analyzer
      │
      ▼
AST Parser
      │
      ├───────────────┐
      ▼               ▼
Security         Complexity
      │               │
      ▼               ▼
Quality        Project Health
      │               │
      └──────┬────────┘
             ▼
      Export Modules
             ▼
      Streamlit Dashboard
```"""

    def _requirements(self) -> str:

        return """- Python 3.10+
- Streamlit
- NetworkX
- Matplotlib
- ReportLab
- OpenPyXL
- Pydantic
- Google Gemini API
- pathlib"""

    def _footer(self) -> str:

        timestamp = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        return (
            "\n---\n\n"
            f"Generated by **{self.GENERATED_BY}**  \n"
            f"Generated on **{timestamp}**\n"
        )

    # ---------------------------------------------------------
    # generate()
    # ---------------------------------------------------------

    def generate(
        self,
        project_name,
        project_summary,
        scores,
        analyses,
    ):
        """
        Generate a professional README.md
        """

        readme = f"# {project_name}\n\n"

        readme += "## 📌 Project Overview\n\n"

        readme += (
            "This project was analyzed using **CodeInsight AI**, "
            "an enterprise static code analysis platform.\n\n"
        )

        readme += "## 📊 Project Statistics\n\n"

        readme += f"- Files: {project_summary.get('files', 0)}\n"
        readme += f"- Functions: {project_summary.get('functions', 0)}\n"
        readme += f"- Classes: {project_summary.get('classes', 0)}\n"
        readme += f"- Lines of Code: {project_summary.get('lines', 0)}\n\n"

        readme += "## ⭐ Quality Scores\n\n"

        for key, value in scores.items():
            readme += f"- **{key.replace('_',' ').title()}** : {value}\n"

        readme += "\n## 🚀 Features\n\n"

        readme += self._feature_list()

        readme += self._section("Installation")
        readme += self._installation()

        readme += self._section("Usage")
        readme += self._usage()

        readme += self._section("Architecture")
        readme += self._architecture()

        readme += self._section("Requirements")
        readme += self._requirements()

        readme += self._footer()

        return readme